### ISSUE TITLE
Missing extra equal sign in fit-sccr.r

### ISSUE THREAD

**Issue by sadatnfs** [b-steve/sscr#1]
Hello! It looks like when the `bobyqa` optimizer was implemented, there was a small bug in that `else if` block, particularly here: 

https://github.com/b-steve/sscr/blob/ee88f97a9b1f2f4c8942e93b79154d6366b14c14/R/fit-sscr.r#L149

**Comment by b-steve** [comment]
Good spotting! This was fixed in f21bf27f63ca5c9a5a6075ee7dfa951da679e0a8.

I am curious to know how you found this bug. As far as I am aware, nobody actually uses this package yet, other than me!

**Comment by sadatnfs** [comment]
No worries. I've been building large Dockers for my institute and I add in any and all packages that I think people can use for their modeling purposes, and I must have added yours along the way sometime!

**Comment by sadatnfs** [comment]
@b-steve Also I'm a big fan of TMB and I've been trying out different implementations of Gaussian Processes in TMB, Tensorflow and PyTorch in order to do some benchmarking on scalability and speed etc., and you have some good looking TMB code I can totally learn from!
